### ISSUE TITLE
Adapters bug in v1.0.0

### ISSUE THREAD

**Issue by ionutfilip** [honza/anosql#35]
Got and error when importing anosql.

```
>>> import anosql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/anosql/__init__.py", line 1, in <module>
    from anosql.core import from_path, from_str, SQLOperationType
  File "/usr/local/lib/python3.7/site-packages/anosql/core.py", line 3, in <module>
    from anosql.adapters.psycopg2 import PsycoPG2Adapter
ModuleNotFoundError: No module named 'anosql.adapters'
```

Step to reproduce:
- install anosql using pip3 : pip3 install anosql
- open a python (v3.6.6) shell and try to import : import anosql

I got no errors downgrading to 0.3.1

**Comment by nackjicholson** [comment]
Thank you! I think this is likely a problem with the `setup.py` file not having reference to the adapters package.

**Comment by nackjicholson** [comment]
```txt
(venv) nackjicholson@Williams-MacBook-Pro-299> pip install git+https://github.com/honza/anosql.git
Collecting git+https://github.com/honza/anosql.git
  Cloning https://github.com/honza/anosql.git to /private/var/folders/_m/ff43p51d5pj0fflyjbvl4cl40000gn/T/pip-req-build-uwnczqhz
Installing collected packages: anosql
  Running setup.py install for anosql ... done
Successfully installed anosql-1.0.1
(venv) nackjicholson@Williams-MacBook-Pro-299> python                 ~/scratch
Python 3.7.1 (default, Nov 11 2018, 11:14:26) 
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import anosql
```

That's from the master branch, commit 5fecd997d9f04059ef6f4eb4c0cf6a5d63b63772

@ionutfilip Can you verify this works for you as well?
@honza Please do a `1.0.1` release from the above master commit once this is verified.

Sorry about the problem! Thanks for reporting!

**Comment by honza** [comment]
Tagged and pushed, thanks @nackjicholson

**Comment by ionutfilip** [comment]
@nackjicholson All good now. Thanks!
